import { readFile } from "node:fs/promises";
import path from "node:path";

import { NextResponse } from "next/server";

import { CONCEPTS, CONCEPT_SWATCH, getConcept, UNITS_PER_CONCEPT } from "@/lib/concepts";
import { PerfectCorpError, runTask, uploadImage } from "@/lib/perfectcorp/client";
import { buildPayload, PayloadError } from "@/lib/perfectcorp/payload";
import {
  fixtureKey,
  forceLive,
  hashBytes,
  offline,
  readFixture,
  writeFixture,
} from "@/lib/perfectcorp/fixtures";

export const runtime = "nodejs";
export const maxDuration = 120;

const MAX_BYTES = 10 * 1024 * 1024;

/** GET /api/concepts — the concept list. Free. */
export function GET() {
  return NextResponse.json({
    unitsPerConcept: UNITS_PER_CONCEPT,
    mode: offline() ? "offline" : forceLive() ? "force-live" : "cache-first",
    concepts: CONCEPTS,
  });
}

/**
 * POST /api/concepts — generate one prewedding concept.
 *
 * multipart/form-data: photo (File), conceptId (string), gender (optional).
 *
 * The output is an AI-generated scene, NOT the uploaded photo with an edit
 * applied. Callers must present it that way.
 */
export async function POST(request: Request) {
  const startedAt = Date.now();

  try {
    let form: FormData;
    try {
      form = await request.formData();
    } catch {
      return bad("expected multipart/form-data with a 'photo' field", "BadRequestBody");
    }

    const photo = form.get("photo");
    if (!(photo instanceof File)) return bad("a 'photo' is required", "MissingPhoto");

    const conceptId = form.get("conceptId");
    if (typeof conceptId !== "string") return bad("'conceptId' is required", "MissingConcept");

    const concept = getConcept(conceptId);
    if (!concept) return bad(`Unknown concept "${conceptId}"`, "UnknownConcept", 404);

    const genderRaw = form.get("gender");
    const gender = genderRaw === "male" ? "male" : "female";

    const photoBytes = new Uint8Array(await photo.arrayBuffer());
    if (photoBytes.byteLength > MAX_BYTES) {
      return bad("photo exceeds the 10 MB limit", "FileTooLarge");
    }

    // The styled endpoints reject a request with no reference (400
    // InvalidParameters) even though the schema marks only `gender` required.
    // This swatch is generated by us, so nothing third-party is shipped.
    const swatch = new Uint8Array(
      await readFile(path.join(process.cwd(), "public", CONCEPT_SWATCH)),
    );

    const identity = { __concept: concept.id, style: concept.style, gender };
    const key = fixtureKey(concept.feature, identity, [hashBytes(photoBytes)]);

    if (!forceLive()) {
      const cached = await readFixture(key);
      if (cached) {
        return NextResponse.json({
          conceptId: concept.id,
          label: concept.label,
          generated: true,
          source: "fixture" as const,
          imageUrl: cached.imagePath,
          unitsSpent: 0,
          unitsSavedByCache: cached.unitsSpent,
          originallyTookMs: cached.elapsedMs,
          totalMs: Date.now() - startedAt,
          key,
        });
      }
    }

    if (offline()) {
      return bad(
        "PERFECTCORP_OFFLINE=1 and no fixture exists for this concept. No credits were spent.",
        "OfflineCacheMiss",
        409,
      );
    }

    const srcFileId = await uploadImage(photoBytes, photo.name || "photo.jpg");
    const refFileId = await uploadImage(swatch, CONCEPT_SWATCH);

    const payload = buildPayload(concept.feature, {
      srcFileIds: [srcFileId],
      refFileId,
      options: { gender, style: concept.style },
    });

    const result = await runTask(concept.feature, payload);

    const fixture = await writeFixture(
      {
        key,
        feature: concept.feature,
        inputs: identity,
        taskId: result.taskId,
        unitsSpent: result.unitsSpent,
        elapsedMs: result.elapsedMs,
        polls: result.polls,
        createdAt: new Date().toISOString(),
      },
      result.url,
    );

    return NextResponse.json({
      conceptId: concept.id,
      label: concept.label,
      generated: true,
      source: "live" as const,
      imageUrl: fixture.imagePath,
      unitsSpent: result.unitsSpent,
      taskId: result.taskId,
      pollMs: result.elapsedMs,
      polls: result.polls,
      totalMs: Date.now() - startedAt,
      key,
    });
  } catch (err) {
    if (err instanceof PayloadError) return bad(`${err.message} (no credits spent)`, err.code);
    if (err instanceof PerfectCorpError) {
      console.error(`[concepts] ${err.code}: ${err.message}`);
      return bad(err.message, err.code, err.httpStatus === 401 ? 401 : 502);
    }
    console.error("[concepts] unexpected:", err);
    return bad("Unexpected server error", "Unexpected", 500);
  }
}

function bad(message: string, code: string, status = 400) {
  return NextResponse.json({ error: message, code }, { status });
}
